env: "local"
http_server:
    address: "localhost:8089"
    timeout: 5s
    idle_timeout: 30s
database_config:
    address: "192.168.3.80"
    port: 5432
    user: "Artem"
    pass: "LEAKYWEBAPPARTEMPASS"
    database: "osuDB"